services:
  nagios:
    build:
      context: .
    container_name: nagios
    restart: unless-stopped
    environment:
      NAGIOS_ADMIN_USER: ${NAGIOS_ADMIN_USER:-nagiosadmin}
      NAGIOS_ADMIN_PASSWORD: ${NAGIOS_ADMIN_PASSWORD:-nagiosadmin}
    ports:
      - "${FORWARD_PORT:-8080}:80"
    volumes:
      - nagios-data:/usr/local/nagios/var

volumes:
  nagios-data:
