services:
  nagios:
    build:
      context: .
    env_file: .env
    ports:
      - "${FORWARD_PORT:-8080}:80"
    volumes:
      - ./etc:/usr/local/nagios/etc
      - ./libexec:/usr/local/nagios/libexec
      - ./var:/usr/local/nagios/var
