services:
  nagios:
    build:
      context: .
    env_file: .env
    ports:
      - "${FORWARD_PORT:-8080}:80"
    volumes:
      - ./etc/nagios.cfg:/usr/local/nagios/etc/nagios.cfg
      - ./etc/objects:/usr/local/nagios/etc/objects
      - ./libexec:/usr/local/nagios/libexec
      - ./var:/usr/local/nagios/var
